### ISSUE TITLE
Runtime Error: SIGSEGV (at address 430968)

### ISSUE THREAD

**Issue by andresayang** [dgaspary/fpOdf#8] opened 2021-03-31 13:06 UTC
Hi,

I'm trying to use fpOdf, well because it is exactly what I need (I need to modify libre office writer document).
When openning a doc, I receive a runtime error:

In procedure TOdfTextDocument.InitBodyContent
whith procedure FreeAndNil(FText);

So I did bypass this, by commenting (I know, it is not how it is supposed to work).

I receive another execption "Mine type not found", when try to write the document with TOdfDocument.SaveToZipFile

I hope you can help (or someone can, thanks

**Comment by dgaspary** [comment] 2021-03-31 13:09
Hi. Could you send me a copy of the file ?

Remove any sensitive data that you feel necessary.

Em qua, 31 de mar de 2021 10:06, andresayang ***@***.***>
escreveu:

**Comment by andresayang** [comment] 2021-03-31 19:27
Hi,

Very nice you reply so fast.
Document sent.
Cheers

**Comment by andresayang** [comment] 2021-03-31 19:28
Another point,

You did very nice stuff, but is there any way to add some helps files (a little more detailed)

Cheers

**Comment by dgaspary** [comment] 2021-03-31 20:46
I don't received the file, possibly due to some filter from github.

You can sent me at my mail dgaspary at gmail.

Again.. Better you remove any sensitive data from the document.. .. 

> You did very nice stuff, but is there any way to add some helps files (a little more detailed)

Unfortunately at the moment is not possible because the code needs a lot of work and is possible it will change at near future. What makes documenting even harder.

You can see some reference code at the "examples" and "test" directories.

Also.. You can ask. I happy to help whenever I have time.

**Comment by dgaspary** [comment] 2021-04-01 16:52
Pushed some Changes that seems to fix the problem. 

It was not necessary to use your file. 

Closing this issue, open a new one in case you have problems somewhere else.

Thank you for reporting and for the help.

**Closed as completed by dgaspary** 2021-04-01 16:52 UTC

**Comment by andresayang** [comment] 2021-04-01 18:08
A small question: If we have document with pictures like the one I sent you, there is no problem, they will be back in modified document ?
(Sorry for my English, I'm french native and language are not our best knowledge (we do prefer wine)
Thanks for the fix, I download right now.

**Comment by dgaspary** [comment] 2021-04-01 18:21
On Thu, Apr 1, 2021 at 3:08 PM andresayang ***@***.***> wrote:

> A small question: If we have document with pictures like the one I sent
> you, there is no problem, they will be back in modified document ?
>

I believe it won't work.

I have not tested, it's not implemented.

You can try the Image test example of joecare99. He has a fork with some
features he added. I could not examine what it did and I had not time at
the moment to talk to him about merging perhaps.


> (Sorry for my English, I'm french native and language are not our best
> knowledge (we do prefer wine)
>

Don't worry. As you learn you gonna note my english is broken too.:)
English is not my native language too, I'm Brazilian.

**Comment by dgaspary** [comment] 2021-04-01 18:24
I was wrong.. Even my master branch have the imageinsert example. 

It was implemented by Joe, this is why I didn't remember the code to be there.

**Comment by andresayang** [comment] 2021-04-01 18:39
Hi,

Sorry again. The problem whith LoadFromZipFile seems to be solved, but "another execption "Mine type not found", when try to write the document with TOdfDocument.SaveToZipFile" still exist:

How to reproduce: create whatever document with office writer, load it with LoadFromZipFile, try to save =>exception "Mime type not found" from function "OdfGetMimeTypeName(AName: string)", AName passed is an empty string.

Sorry,

Thanks

**Comment by dgaspary** [comment] 2021-04-01 18:43
On Thu, Apr 1, 2021 at 3:39 PM andresayang ***@***.***> wrote:

> Hi,
>
> Sorry again. The problem whith LoadFromZipFile seems to be solved, but
> "another execption "Mine type not found", when try to write the document
> with TOdfDocument.SaveToZipFile" still exist:
>
> How to reproduce: create whatever document with office writer, load it
> with LoadFromZipFile, try to save =>exception "Mime type not found" from
> function "OdfGetMimeTypeName(AName: string)", AName passed is an empty
> string.
>

I'll take a look later today.

Thank you

**Comment by dgaspary** [comment] 2021-04-01 21:31
On Thu, Apr 1, 2021 at 3:42 PM Daniel Gaspary ***@***.***> wrote:
>
>> How to reproduce: create whatever document with office writer, load it with LoadFromZipFile, try to save =>exception "Mime type not found" from function "OdfGetMimeTypeName(AName: string)", AName passed is an empty string.
>
> I'll take a look later today.

I could not reproduce the problem. I tried with:

var
   doc: TOdfDocument;
begin
     doc:=TOdfTextDocument.LoadFromZipFile('/tmp/test.odt','/tmp/temp01');
     doc.SaveToZipFile('/tmp/test_out.odt');

**Comment by andresayang** [comment] 2021-04-01 21:49
Ok, 
Sorry, my fault ...
I did doc:=TOdfDocument.LoadFromZipFile('/tmp/test.odt','/tmp/temp01'); trying to get back all original folders back in zip, as I need at least Pictures folder back.

Now I got to figure out how to put back all "odt" content (only META-INF folder is keept - recreated)

**Comment by dgaspary** [comment] 2021-04-01 21:54
On Thu, Apr 1, 2021 at 6:49 PM andresayang ***@***.***> wrote:

> Ok,
> Sorry, my fault ...
> I did doc:=TOdfDocument.LoadFromZipFile('/tmp/test.odt','/tmp/temp01');
> trying to get back all original folders back in zip, as I need at least
> Pictures folder back.
>
> Now I got to figure out how to put back all "odt" content (only META-INF
> folder is keept - recreated)
>

ok.


When you have some specific problem, just let me know.

I used to work more often with flat files (not the zip version), that is
why some errors with LoadFromZip/SaveToZip are new to me.

**Comment by andresayang** [comment] 2021-04-01 22:25
Well,

I think I'll have to modify a little:
1) To do not delete original temp unzipped dir
2) Manage to recover original temp unzipped dir, except modified files (mainly content.xml).

Thanks

**Comment by dgaspary** [comment] 2021-04-01 22:47
On Thu, Apr 1, 2021 at 7:25 PM andresayang ***@***.***> wrote:
>
> Well,
>
> I think I'll have to modify a little:
>
> To do not delete original temp unzipped dir
> Manage to recover original temp unzipped dir, except modified files (mainly content.xml).

I have tested and found the problem you said earlier. I need to figure
out how to solve this problem. As you said, maybe I will need to avoid
deleting the temp dir.

I created a new issue for this problem, please reply there: issue #9
